version: "3.2"

 # Starts ebics-service with a libeufin as a banking backend
 

services:
  postgres: 
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=pgrootuser
      - POSTGRES_PASSWORD=pgrootpassword
      - POSTGRES_DB=libeufindb
      - POSTGRES_NON_ROOT_USER=pguser
      - POSTGRES_NON_ROOT_PASSWORD=pgpassword
      # - PGDATA="/var/lib/postgresql/data/pgdata"
   # ports:
     # - "5432:5432"  
  #volumes:
      #- ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      # GCP: - /mnt/stateful_partition/APP/postgres/db:/var/lib/postgresql/data/pgdata
      # local dir: - ${DATADIR:?}/postgres:/var/lib/postgresql/data

  libeufin: 
    # image: e36io/libeufin:mergeLibeufin
    build: 
      context: /home/w/ghvlada/LibEuFin   
    depends_on: 
      - postgres
    environment:
      - LIBEUFIN_SANDBOX_URL=http://localhost:5016/
      - LIBEUFIN_SANDBOX_DB_CONNECTION=jdbc:postgresql://postgres:5432/libeufindb?user=pgrootuser&password=pgrootpassword
      - LIBEUFIN_NEXUS_DB_CONNECTION=jdbc:postgresql://postgres:5432/libeufindb?user=pgrootuser&password=pgrootpassword
      - LIBEUFIN_NEXUS_URL=http://localhost:5000/
      - LIBEUFIN_NEXUS_USERNAME=foo
      - LIBEUFIN_NEXUS_PASSWORD=superpassword
      - LIBEUFIN_SANDBOX_ADMIN_PASSWORD=superpassword
      - LIBEUFIN_SANDBOX_USERNAME=admin
      - LIBEUFIN_SANDBOX_PASSWORD=superpassword

      - EBICS_BASE_URL=http://localhost:5016/ebicsweb
      - POSTGRES_USER=pgrootuser
      - POSTGRES_PASSWORD=pgrootpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=libeufindb
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      
    command: /app/scripts/init_libeufin_sandbox.sh
    tty: true
    stdin_open: true # without this node doesn't start; https://stackoverflow.com/questions/61857267/how-to-make-yarn-start-work-inside-docker-image-with-react-scripts-3-4-and-babel
    ports:
      - "5016:5016" # sandbox 
      - "5001:5000" # nexus
      - "3000:3000" # ui - login: foo/superpassword
    expose:
      - 5016
      - 3000
      - 5001
    volumes:
      - ./scripts:/app/scripts
      - ./trace:/app/trace:rw
  
  ebics-service: 
    #image: e36io/ebics-service:updateLibeufin
    build: 
      context: .    
    depends_on: 
      - libeufin
    environment:
       - spring_profiles_active=sandbox
       - LIBEUFIN_SANDBOX_URL=http://libeufin:5016 # overwrite localhost in configs
       - LIBEUFIN_NEXUS_URL=http://libeufin:5000
       - LIBEUFIN_SANDBOX_ADMIN_PASSWORD=superpassword
       - LIBEUFIN_SANDBOX_USERNAME=admin
       - LIBEUFIN_SANDBOX_PASSWORD=superpassword       
    ports:
      - "8093:8093"
    expose:
      - 8093      

  hyperfridge: 
    # profiles:
    #   - dev      
    container_name: hyperfridge
    # image: e36io/hyperfridge-r0:latest
    build: 
      context: /home/w/workspace/hyperfridge-r0  
    environment:
      TEST: 'true'  # Ensure this is a string, not a boolean
    volumes:
      - ./scripts:/app/scripts:ro
      - ./trace:/app/trace:ro
      
    
  
  pgadmin: 
    # profiles:
    #   - dev      
    container_name: libfineugadmin
    image: dpage/pgadmin4:7.6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
      MAX_LOGIN_ATTEMPTS: '15'  # Ensure this is a string, not a number
      POSTGRES_USER: pgrootuser
      POSTGRES_PASSWORD: pgrootpassword
      POSTGRES_HOST: postgres
      POSTGRES_DB: libeufindb
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'  # Ensure this is a string, not a boolean

    depends_on: 
      - postgres
    volumes:
      - /home/w/pgadmin:/var/lib/pgadmin:rw
    user: root
    ports:
      - "53603:53603"
      - "8081:80" #mapped on w.e36.io:35050; admin@example.com root; add server medi medi medi