version: "3.2"

 # Starts ebics-service with a libeufin as a banking backend
 

services:
  postgres: 
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=pgrootuser
      - POSTGRES_PASSWORD=pgrootpassword
      - POSTGRES_DB=libeufindb
      - POSTGRES_NON_ROOT_USER=pguser
      - POSTGRES_NON_ROOT_PASSWORD=pgpassword
      # - PGDATA="/var/lib/postgresql/data/pgdata"
   # ports:
     # - "5432:5432"  
  #volumes:
      #- ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      # GCP: - /mnt/stateful_partition/APP/postgres/db:/var/lib/postgresql/data/pgdata
      # local dir: - ${DATADIR:?}/postgres:/var/lib/postgresql/data

  libeufin: 
    image: e36io/libeufin:updateLibeufin
    depends_on: 
      - postgres
    environment:
      - LIBEUFIN_SANDBOX_URL=http://localhost:5016/
      - LIBEUFIN_SANDBOX_DB_CONNECTION=jdbc:postgresql://postgres:5432/libeufindb?user=pgrootuser&password=pgrootpassword
      - LIBEUFIN_NEXUS_DB_CONNECTION=jdbc:postgresql://postgres:5432/libeufindb?user=pgrootuser&password=pgrootpassword
      - LIBEUFIN_NEXUS_URL=http://localhost:5000/
      - EBICS_BASE_URL=http://localhost:5016/ebicsweb
      - POSTGRES_USER=pgrootuser
      - POSTGRES_PASSWORD=pgrootpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=libeufindb
      
    command: /app/scripts/init_libeufin_sandbox.sh
    tty: true
    stdin_open: true # without this node doesn't start; https://stackoverflow.com/questions/61857267/how-to-make-yarn-start-work-inside-docker-image-with-react-scripts-3-4-and-babel
    ports:
      - "5016:5016" # sandbox 
      - "5000:5000" # nexus
      - "3000:3000" # ui
    volumes:
      - ./scripts:/app/scripts
  
  ebics-service: 
    image: e36io/ebics-service:main
    depends_on: 
      - libeufin
    environment:
       - spring_profiles_active=sandbox
       - LIBEUFIN_SANDBOX_URL=http://libeufin:5016 # overwrite localhost in configs
       - LIBEUFIN_NEXUS_URL=http://libeufin:5000
    ports:
      - "8093:8093"

